name: Build

on:
  workflow_dispatch:
  pull_request:

permissions: read-all

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: |
          cd ./backend
          go build -v ./cmd/main.go

  # check-bats-version:
  # hogehoge:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "this is pen"
  #     - uses: actions/checkout@v3
  #     - run: |
  #         ls -al
  #         echo "hogehoge"
  #     - run: echo "This job's status is ${{ job.status }}."
  #     - run: echo "This workflow is ${{ github.workflow }}."
  #     - run: echo "This repository status is ${{ github.repository }}."