name: GO VET

on:
  workflow_dispatch:
  pull_request:

permissions: read-all

jobs:
  go_vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: GO vet
        run: |
          cd ./backend
          go vet ./...